SET IDENTITY_INSERT dbo.CLIENTE ON
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (1, 'LUCAS', '83988475825', 'TESTE@GMAIL.COM', 123456, '1546846541684');
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (2, 'GABRIEL', '85646454825', 'TESTE@GMAIL.COM', 123456, '65465465484');
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (3, 'ANTONIO', '83988465585', 'TESTE@GMAIL.COM', 123456, '154645787544');
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (4, 'MANOEL', '83999475825', 'TESTE@GMAIL.COM', 1234567, '4785846541684');
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (5, 'JOSE', '83995474725', 'TESTE@GMAIL.COM', 12345, '5465454654654');
SET IDENTITY_INSERT dbo.CLIENTE OFF

ALTER TABLE DBO.CLIENTE.NOME MODIFY COLUMN C
	
SELECT * FROM DBO.CLIENTE c 

SET IDENTITY_INSERT dbo.DOCUMENTARIOS ON
INSERT INTO dbo.DOCUMENTARIOS (ID, NOME, IDIOMA, LEGENDA, ANO, TEMPORADA, DURACAO, NUMEROEP) VALUES (1, 'AS TRANÇAS DO REI CARECA', 'PORTUGUES', 'FALSE', '2022-05-05', 1, '02:14', 15);
INSERT INTO dbo.DOCUMENTARIOS (ID, NOME, IDIOMA, LEGENDA, ANO, TEMPORADA, DURACAO, NUMEROEP) VALUES (2, 'DOM QUIXOTE DE LA MANCHA', 'PORTUGUES', 'FALSE', '2012-07-05', 1, '01:45', 8);
INSERT INTO dbo.DOCUMENTARIOS (ID, NOME, IDIOMA, LEGENDA, ANO, TEMPORADA, DURACAO, NUMEROEP) VALUES (3, 'POEIRA EM ALTO MAR', 'PORTUGUES', 'FALSE', '2015-05-25', 1, '00:51', 20);
INSERT INTO dbo.DOCUMENTARIOS (ID, NOME, IDIOMA, LEGENDA, ANO, TEMPORADA, DURACAO, NUMEROEP) VALUES (4, 'A VOLTA DOS QUE NÃO FORAM', 'PORTUGUES', 'FALSE', '2008-07-14', 1, '00:30', 7);
SET IDENTITY_INSERT dbo.DOCUMENTARIOS OFF

SELECT * FROM DBO.DOCUMENTARIOS d 

SET IDENTITY_INSERT dbo.FILMES  ON
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (001, 'Convite Maldito', 'INGLES', 'TRUE', '2022-08-25');
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (002, 'Sorria', 'INGLES', 'TRUE', '2022-07-29');
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (003, 'Halloween Ends - O Acerto de Contas Final', 'INGLES', 'TRUE', '2022-10-13');
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (004, 'A Mulher Rei', 'PORTUGUES', 'TRUE', '2022-07-22');
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (005, 'Amsterdam', 'INGLES', 'TRUE', '2022-10-06');
SET IDENTITY_INSERT dbo.FILMES  OFF

SELECT * FROM DBO.FILMES f 

SET IDENTITY_INSERT dbo.MENSALIDADE ON
INSERT INTO DBO.MENSALIDADE (ID, VALOR, RENOVACAOASSINATURA, IDCLIENTE, DATAPAGAMENTO) VALUES (01, 15.50, 'NÃO', 1, '2022-09-11');
SET IDENTITY_INSERT dbo.MENSALIDADE OFF

SELECT * FROM DBO.MENSALIDADE m 

SET IDENTITY_INSERT dbo.SERIES ON
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEROEPS, LEGENDAS) VALUES (1, 'O Clube da Meia Noite', 2, 'Sete jovens com doenças terminais passam os seus últimos dias de vida no hospício', '2022-01-01', '05:15', 'ALEMÃO', 7, 'TRUE');
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEROEPS, LEGENDAS) VALUES (2, '9-1-1', 2, '911 é o número de telefone discado em casos de emergência e, por meio deles, diversas vítimas conseguem ser salvas.', '2018-01-01', '00:35:15', 'INGLÊS', 8, 'TRUE');
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEROEPS, LEGENDAS) VALUES (3, 'Ruptura', 5, 'Cinco funcionários aceitam participar de um procedimento que separa permanentemente suas memórias pessoais das do trabalho. Mas por trás dessa estranha cirurgia, existem segredos impensáveis.', '2022-01-01', '00:55:20', 'INGLÊS', 15, 'TRUE');
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEROEPS, LEGENDAS) VALUES (4, 'O Filho BAstardo do Diabo', 1, 'O Filho Bastardo do Diabo é uma série britânica de fantasia original Netflix baseada na trilogia de livros Half Bad, escrita por Sally Green. A história gira em torno de Nathan, um adolescente que é o filho ilegítimo do bruxo mais temido do mundo.', '2022-01-01', '00:55:15', 'ALEMÃO', 9, 'TRUE');
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEROEPS, LEGENDAS) VALUES (5, 'Periféricos', 5, 'Depois que seu irmão consegue um emprego em uma empresa de tecnologia, Flynn descobre um mundo virtual que pode estar mais próximo da realidade do que eles imaginam.', '2022-01-01', '00:47:35', 'PORTUGUES', 20, 'TRUE');
SET IDENTITY_INSERT dbo.SERIES OFF

SELECT * FROM dbo.SERIES s 

SET IDENTITY_INSERT dbo.VIDEOS  ON
INSERT INTO DBO.VIDEOS (ID, TITULO, GENREO, DURACAO, PRODUTORA, SINOPSE, DIRETOR) VALUES (1, 'VIDEO 1', 'FEMININO', '05:05', 'ANONIMA', 'ALGO ENGRAÇADO', 'MESSIAS');
INSERT INTO DBO.VIDEOS (ID, TITULO, GENREO, DURACAO, PRODUTORA, SINOPSE, DIRETOR) VALUES (2, 'VIDEO 2', 'M', '08:10', 'ANONIMA', 'ALGO LEGAL', 'GABRIEL');
INSERT INTO DBO.VIDEOS (ID, TITULO, GENREO, DURACAO, PRODUTORA, SINOPSE, DIRETOR) VALUES (3, 'VIDEO 3', 'F', '07:55', 'ANONIMA', 'ENGRAÇADO', 'COLETIVO 401');
INSERT INTO DBO.VIDEOS (ID, TITULO, GENREO, DURACAO, PRODUTORA, SINOPSE, DIRETOR) VALUES (4, 'VIDEO 4', 'F', '04:41', 'VIDEOS ONLINE', 'ALGO', 'UNIESP');
INSERT INTO DBO.VIDEOS (ID, TITULO, GENREO, DURACAO, PRODUTORA, SINOPSE, DIRETOR) VALUES (5, 'VIDEO 5', 'M', '05:25', 'PESSOAL', 'ANONIMO', 'MESSIAS');
SET IDENTITY_INSERT dbo.VIDEOS  OFF

SELECT * FROM DBO.VIDEOS v 










