CREATE TABLE CLIENTES (
	IDCLIENTES INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(100),
	TELEFONE VARCHAR(13),
	EMAIL VARCHAR (100),
	SENHA VARBINARY(8000),
	CARTAOCREDITO VARCHAR (16),
);

select * from CLIENTES ;

CREATE TABLE VIDEOS(
	IDVIDEOS INT PRIMARY KEY NOT NULL NOT NULL,
	TITULOVIDEO VARCHAR (100),
	PRODUTORA VARCHAR (100),
	DURACAO TIME(5),
);
	
select * from VIDEOS;

CREATE TABLE AVALIACAO(
	IDAVALIACAO INT PRIMARY KEY NOT NULL,
	NOTA CHAR (5),
);

select * from CLIENTES c  ;

CREATE TABLE SERIES(
	IDSERIE INT PRIMARY KEY NOT NULL,	
	NOME VARCHAR(50),
	TEMPORADA CHAR(20),
	ANO DATE,
	IDGENERO INT,
	DURACAO TIME(5),
	IDIOMA CHAR(255),
	NUMEROEPS INT,
	LEGENDAS VARCHAR(300),
);

ALTER TABLE SERIES 
	ADD CONSTRAINT fk_GENEROS FOREIGN KEY (IDGENERO) REFERENCES GENEROS (IDGENERO);

EXEC sp_RENAME 'CLIENTES.ID', 'IDCLIENTES', 'COLUMN';
	
CREATE TABLE GENEROS(
	IDGENERO INT PRIMARY KEY NOT NULL,
	NOMEGENERO VARCHAR (100),
);
	
EXEC sp_RENAME 'GENEROS.ID', 'IDGENERO', 'COLUMN';


CREATE TABLE MENSALIDADE(
	IDMENSALIDADE INT PRIMARY KEY NOT NULL,
	VALOR FLOAT(50),
	RENOVACAOASSINATURA VARCHAR(50),
	IDCLIENTE INT,
	DATAINICIO DATETIME,
 );

select * from MENSALIDADE;

ALTER TABLE MENSALIDADE 
	ADD CONSTRAINT fk_CLIENTES FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES (IDCLIENTES);

ALTER TABLE

CREATE TABLE FILMES(
	IDFILME INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(200),
	IDIOMA CHAR(255),
	LEGENDA VARCHAR(300),
	IDGENERO INT,
	ANO DATE,
);

CREATE TABLE DOCUMENTARIOS(
	IDDOC INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(200),
	IDIOMA CHAR(255),
	LEGENDA VARCHAR(300),
	IDGENERO INT,
	ANO DATE,
	TEMPORADA CHAR(20),
	DURACAO TIME(5),
	NUMEROEP INT
);
